apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nreo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0037-tenant/tkrw-pr712-0075-0037-app/devfile-sample-nreo@sha256:dfdf5a318562875a9bb4a0c21fa5c294c604f86be85998b0b7092b57611ff41f
        name: my-nodejs
        resources: {}
status: {}
